# Build stage
FROM golang:1.24-alpine AS builder
WORKDIR /app

# Copy go mod and sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code
COPY . .

# Build the application
RUN CGO_ENABLED=0 GOOS=linux go build -o event-manager-api ./cmd/...

# Final stage
FROM alpine:latest
WORKDIR /app

# Copy the binary from builder
COPY --from=builder /app/event-manager-api .

# Expose the port the app runs on
EXPOSE 8080

# Command to run the executable
CMD ["./event-manager-api"]
